# app/config/security.yml

security:
  encoders:
    DEE\UserBundle\Entity\User:                 sha512

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
        id: fos_user.user_provider.username

  firewalls:
    dev:
      pattern:      ^/(_(profiler|wdt)|css|images|js)/
      security:     false
      
    main:
        pattern:        ^/
        anonymous:      true
        provider:       main
        form_login: 
            login_path: fos_user_security_login
            check_path: fos_user_security_check
            # login success redirecting options 
            # found on symfony documentation : http://symfony.com/doc/current/reference/configuration/security.html#redirecting-after-login (line 150 to 154)
            always_use_default_target_path: true
            default_target_path:            /users/admin
        
        logout:
            path:       fos_user_security_logout
            target:     /users/login
        remember_me:
            secret:     %secret%
            
          

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }

    
