<?php

namespace DEE\FtpBundle\Repository;

/**
 * FtpFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FtpFileRepository extends \Doctrine\ORM\EntityRepository
{
}
