<?php

namespace DEE\FtpBundle\Repository;

/**
 * FtpFileCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FtpFileCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
