<?php

namespace DEE\FtpBundle\Repository;

/**
 * UploadedFileCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UplFileCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
