# Lesson routes
dee_lesson_delete:
    path: /lessons/delete/{id}
    defaults:
        _controller: DEECoursesBundle:Lesson:delete
    requirements:
        id: \d+

# Exam routes
dee_exam_delete:
    path: /exams/delete/{id}
    defaults:
        _controller: DEECoursesBundle:Exam:delete
    requirements:
        id: \d+

# Student routes
dee_student_showcourse:
    path: /students/showcourse/{id}
    defaults:
        _controller: DEECoursesBundle:Student:showCourse
    requirements:
        id: \d+

dee_student_delete:
    path: /students/delete/{id}
    defaults:
        _controller:   DEECoursesBundle:Student:delete
    requirements:
        id: \d+
     
dee_student_homepage:
      path: /students/
      defaults:
          _controller:  DEECoursesBundle:Student:index
  
# ExamType routes          
dee_examtype_delete:
    path: /examtypes/delete/{id}
    defaults:
        _controller:   DEECoursesBundle:ExamType:delete
    requirements:
        id: \d+
     
dee_examtype_homepage:
      path: /examtypes/
      defaults:
          _controller:  DEECoursesBundle:ExamType:index
