dee_student_delete:
    path: /delete/{id}
    defaults:
        _controller:   DEECoursesBundle:Student:delete
    requirements:
        id: \d+
     
          
dee_student_homepage:
      path: /
      defaults:
          _controller:  DEECoursesBundle:Student:index
