<?php

namespace DEE\CoursesBundle\Repository;

/**
 * ExamCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
