<?php

namespace DEE\CoursesBundle\Repository;

/**
 * ExamTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
