<?php

namespace DEE\CoursesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWhereStudentQueryBuilder($studentId) {
        return $this->createQueryBuilder('e')
                    ->where('e.student = :student')
                    ->setParameter('student', $studentId);
    }
}
