dee_core_home:
    path:     /
    defaults: { _controller: DEECoreBundle:Core:index }
    
dee_core_contact:
    path:       /contact
    defaults:   { _controller: DEECoreBundle:Core:contact }

dee_core_prices:
    path:       /prices
    defaults:   { _controller: DEECoreBundle:Core:prices }